// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzCxAltwFIT9bfLcaoDmpgMp-cC_WTkM',
    appId: '1:594684793351:web:473867ad983740590310a2',
    messagingSenderId: '594684793351',
    projectId: 'remotesensing-0ae21',
    authDomain: 'remotesensing-0ae21.firebaseapp.com',
    storageBucket: 'remotesensing-0ae21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SC96d53Siu9iqRtfAUuczZ2aTknEvU8',
    appId: '1:594684793351:android:1d98894428350acf0310a2',
    messagingSenderId: '594684793351',
    projectId: 'remotesensing-0ae21',
    storageBucket: 'remotesensing-0ae21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOfS6TQgF8r4Zdyd_NR7dQhq73Vh-x6GI',
    appId: '1:594684793351:ios:1bd03fc31199dc160310a2',
    messagingSenderId: '594684793351',
    projectId: 'remotesensing-0ae21',
    storageBucket: 'remotesensing-0ae21.appspot.com',
    iosBundleId: 'com.example.remoteSensing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOfS6TQgF8r4Zdyd_NR7dQhq73Vh-x6GI',
    appId: '1:594684793351:ios:1bd03fc31199dc160310a2',
    messagingSenderId: '594684793351',
    projectId: 'remotesensing-0ae21',
    storageBucket: 'remotesensing-0ae21.appspot.com',
    iosBundleId: 'com.example.remoteSensing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwzCxAltwFIT9bfLcaoDmpgMp-cC_WTkM',
    appId: '1:594684793351:web:5ef826b84f219b380310a2',
    messagingSenderId: '594684793351',
    projectId: 'remotesensing-0ae21',
    authDomain: 'remotesensing-0ae21.firebaseapp.com',
    storageBucket: 'remotesensing-0ae21.appspot.com',
  );

}